#!/bin/sh

set -e

if [ -f /usr/share/debconf/confmodule ]; then
    . /usr/share/debconf/confmodule
fi

if [ "$1" = "purge" ]; then
    for config_file in "config.json" "use_authbind"; do
        rm -f /etc/poker-terminator-front/$config_file
    done
    if which ucf >/dev/null 2>&1; then
        ucf --purge /etc/poker-terminator-front/config.json
        ucfr --purge poker-terminator-front /etc/poker-terminator-front/config.json
    fi
fi

#DEBHELPER#

exit 0
