#!/bin/bash -e
# do NOT remove -e !

BASE_PATH="$(dirname $0)"
FOREVER="${BASE_PATH}/node_modules/.bin/forever"
COFFEE="${BASE_PATH}/node_modules/.bin/coffee"
AUTHBIND=$(which authbind)
PIDFILE="/var/run/poker-terminator.pid"

USE_AUTHBIND=$(cat /etc/poker-terminator/use_authbind) || exit 1

LOGFILE="$1"
LOG_TO_SYSLOG="$2"

if [ -z "$LOGFILE" -a $LOG_TO_SYSLOG -ne 1 ]; then
	echo "logfile not passed"
	exit 1
fi

# check if pidfiles are writable and create them if necessary
touch "$PIDFILE"

# if a process is still running, quit
# (this should be covered by forever. but it is not)
OLD_PID=$(cat "$PIDFILE")
[ -n "$OLD_PID" ] && ls /proc/$OLD_PID && {
	echo "process already running"
	exit 1
}

# augment FOREVER by adding authbind to it, if needed
if [ $USE_AUTHBIND -eq 1 ]; then
	 FOREVER="$AUTHBIND --deep $FOREVER"
elif [ $USE_AUTHBIND -ne 0 ]; then
	echo "error validating authbind usage in /etc/poker-terminator/use_authbind. 0 or 1 are valid values"
	exit 1
fi

if [ $LOG_TO_SYSLOG -ne 1 ]; then
    touch "$LOGFILE"
fi

# common arguments for forever start
FOREVER_COMMON_ARGS="--sourceDir $BASE_PATH --pidFile $PIDFILE --minUptime 60000 --spinSleepTime 10000 --command $COFFEE server.coffee"

# run forever with all settings
cd $BASE_PATH
if [ $LOG_TO_SYSLOG -eq 1 ]; then
	$FOREVER start \
		-a \
		-l >(logger -t forever -p user.info) \
		-o >(logger -t poker-terminator -p user.info) \
		-e >(logger -t poker-terminator -p user.error) \
		$FOREVER_COMMON_ARGS
else
	$FOREVER start \
		-a \
		-l $LOGFILE \
		-o $LOGFILE \
		-e $LOGFILE \
		$FOREVER_COMMON_ARGS
fi
